// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A Genkit flow for suggesting relevant tags for portfolio items using GenAI.
 *
 * - suggestPortfolioTags - A function that suggests tags for a given portfolio item description.
 * - SuggestPortfolioTagsInput - The input type for the suggestPortfolioTags function.
 * - SuggestPortfolioTagsOutput - The return type for the suggestPortfolioTags function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPortfolioTagsInputSchema = z.object({
  description: z.string().describe('The description of the portfolio item.'),
});
export type SuggestPortfolioTagsInput = z.infer<typeof SuggestPortfolioTagsInputSchema>;

const SuggestPortfolioTagsOutputSchema = z.object({
  tags: z.array(z.string()).describe('An array of suggested tags for the portfolio item.'),
});
export type SuggestPortfolioTagsOutput = z.infer<typeof SuggestPortfolioTagsOutputSchema>;

export async function suggestPortfolioTags(input: SuggestPortfolioTagsInput): Promise<SuggestPortfolioTagsOutput> {
  return suggestPortfolioTagsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPortfolioTagsPrompt',
  input: {schema: SuggestPortfolioTagsInputSchema},
  output: {schema: SuggestPortfolioTagsOutputSchema},
  prompt: `You are an expert at suggesting relevant tags for portfolio items.

  Based on the following description, suggest a list of tags that would be relevant for this portfolio item.
  Return the tags as a JSON array of strings.

  Description: {{{description}}}
  `,
});

const suggestPortfolioTagsFlow = ai.defineFlow(
  {
    name: 'suggestPortfolioTagsFlow',
    inputSchema: SuggestPortfolioTagsInputSchema,
    outputSchema: SuggestPortfolioTagsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
